# Generated by Django 4.0.4 on 2022-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Book description', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='ecrivain',
            field=models.CharField(default='Book author', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
