# Generated by Django 4.0.4 on 2022-05-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_description_product_ecrivain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default=' ', upload_to='static/images'),
        ),
    ]
